# /home/yoon/my_final_slam_params.yaml
slam_toolbox:
  ros__parameters:
    use_sim_time: False

    # KTX 속도에 맞춰 공장 라인을 조절하는 핵심 파라미터
    transform_timeout: 1.0     # 부품(TF)을 1초간 기다려줌
    tf_buffer_duration: 45.0   # 과거 부품 정보를 45초간 보관
    throttle_scans: 3          # 들어오는 부품 3개 중 1개만 처리
    scan_queue_size: 50        # 컨베이어 벨트 크기를 넉넉하게
    map_update_interval: 2.0   # 2초에 한 번만 결과 보고

    # 기본 설정
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping
