# 파일 경로: ~/my_turtlebot_ws/param/explore_params.yaml

explore_node:
  ros__parameters:
    # --- 기본 설정 ---
    use_sim_time: True
    costmap_topic: "global_costmap/costmap"
    robot_base_frame: "base_link"
    transform_tolerance: 1.0
    visualize: True

    # --- 탐색 행동 및 종료 조건 설정 ---
    min_frontier_size: 0.3
    progress_timeout: 10.0
    planner_frequency: 1.0
    return_to_init: False

    # --- 탐색 성향 결정 (효율성 중시) ---
    potential_scale: 3.0
    gain_scale: 1.0
    orientation_scale: 0.5

